# Generated by Django 3.0.6 on 2020-06-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TenderReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('photo_upload', models.FileField(upload_to='uploads/')),
                ('date_published', models.DateField(auto_now=True)),
                ('sides', models.CharField(max_length=100)),
                ('sauces', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('recommend', models.BooleanField(null=True)),
            ],
        ),
    ]
