# Generated by Django 3.0.6 on 2020-06-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendersapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tenderreview',
            name='rating',
            field=models.IntegerField(default=4.5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenderreview',
            name='user_name',
            field=models.CharField(default=4, max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tenderreview',
            name='business',
        ),
        migrations.AddField(
            model_name='tenderreview',
            name='business',
            field=models.ManyToManyField(related_name='restaurant', to='tendersapp.Restaurant'),
        ),
    ]
